### PR TITLE
Fixed issue #4: Create topbar component

### PR DESCRIPTION
**Pull request by devanshusingla**
Created topbar with material UI having default light blue color.

### CODE REVIEW

**Comment by yashsriv** [comment]
Hi! Are you following some guide for learning react? I'd like to know the reason behind using [class-based react component vs function based](https://medium.com/@Zwenza/functional-vs-class-components-in-react-231e3fbd7108).

I think the general/latest recommendation is to use function based react components as they are simpler and some amazing work (react hooks) has been done in the past one year to make them as powerful, if not more, as class based react components.

Regarding the `console.log('opened')` you have in the js body -> this will be called as soon as the Javascript File is loaded and has got nothing to do with the actual component being displayed. If you want a log on the component being loaded, the class based react component way to do this would be to have it in the `onComponentMounted` function of the class. There's a functional component way of doing this too but I won't make this comment longer than it already has become :P

**Comment by devanshusingla** [comment]
I'm still new to react but yeah think so got your point and will try to implement the code in functional.

**Comment by devanshusingla** [comment]
changed the implementation to the functional one and removed console.log messages.

**Comment by devanshusingla** [comment]
Screenshot from 2020-04-08 19-42-01

**Pull request merged**
